services:
    command_bus:
        public: true
        class: Tactics\CommandBusBundle\CommandBus\SimpleCommandBus
        arguments:
            - '@short_name_strategy'
    short_name_strategy:
        class: Tactics\CommandBusBundle\NamingStrategy\ShortNameStrategy
